/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgePricing: typeof import('./components/AgePricing.vue')['default']
    ApplyDiscount: typeof import('./components/drawer/ConfigList.vue')['default']
    ConfigList: typeof import('./components/drawer/ConfigList.vue')['default']
    PlanChoices: typeof import('./components/agePricing/PlanChoices.vue')['default']
    PricingTables: typeof import('./components/PricingTables.vue')['default']
    ReferenceLabel: typeof import('./components/ReferenceLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./components/agePricing/TextInput.vue')['default']
  }
}
